all:
	g++ -I/home/teta/Folder/OGDF/include -O2 dimacs.cpp -o test -L/home/teta/Folder/OGDF/ -lOGDF -lCOIN -g

genetic:
	g++ -I/home/teta/Folder/OGDF/include -O2 dimacs_genetic.cpp -o test -L/home/teta/Folder/OGDF/ -lOGDF -lCOIN -g

strat1:
	g++ -I/home/teta/Folder/OGDF/include -O2 dimacs_estrategia1.cpp -o test -L/home/teta/Folder/OGDF/ -lOGDF -lCOIN -g

strat2:
	g++ -I/home/teta/Folder/OGDF/include -O2 dimacs_estrategia2.cpp -o test -L/home/teta/Folder/OGDF/ -lOGDF -lCOIN -g

partition:
	g++ -I/home/teta/Folder/OGDF/include -O2 dimacs_partition.cpp -o test -L/home/teta/Folder/OGDF/ -lOGDF -lCOIN -g
